apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order-service-stage
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8300        # Ajusta el puerto según tu configuración
      targetPort: 8300
  type: ClusterIP
