pipeline {
    agent any

    environment {
        SERVICE_NAME = 'product-service'
        IMAGE_NAME = "johandiaz9021/product-service:latest"
        NAMESPACE = 'product-service-master'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/JohanDiaz9021/ecommerce-microservice-user-service.git'
            }
        }

        stage('Unit Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    bat 'mvnw.cmd test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("${SERVICE_NAME}") {
                    bat "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat "echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin"
                    bat "docker push ${IMAGE_NAME}"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir("${SERVICE_NAME}/k8s") {
                    bat "kubectl apply -f deployment.yaml --namespace=${NAMESPACE}"
                    bat "kubectl apply -f service.yaml --namespace=${NAMESPACE}"
                }
            }
        }
    }

    stage('Generate Release Notes') {
        steps {
            script {
                bat "echo 'Release Notes: Despliegue automático de ${SERVICE_NAME} en namespace ${NAMESPACE} con pruebas unitarias exitosas.' > release-notes.txt"
                archiveArtifacts artifacts: 'release-notes.txt', fingerprint: true
            }
        }
    }
}