apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service-master
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8400 
  type: ClusterIP
