apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service-master
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80          # Puerto de acceso al servicio dentro del cluster
      targetPort: 8400  # Puerto donde corre la aplicación dentro del contenedor
  type: ClusterIP
