apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: proxy-client-master  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
        - name: proxy-client
          image: johandiaz9021/proxy-client:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: proxy-client-master  
spec:
  selector:
    app: proxy-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
