apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: proxy-client-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
      - name: proxy-client
        image: johandiaz9021/proxy-client:latest
        ports:
        - containerPort: 8080
