apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: proxy-client-stage
spec:
  selector:
    app: proxy-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
