apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: favourite-service-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
        - name: favourite-service
          image: johandiaz9021/favourite-service:latest
          ports:
            - containerPort: 8080
