apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: favourite-service-stage
spec:
  selector:
    app: favourite-service
  ports:
    - protocol: TCP
      port: 8080            # Puerto externo del servicio
      targetPort: 8080      # Puerto en el contenedor
  type: ClusterIP
