apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: service-discovery-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: johandiaz9021/service-discovery:latest
        ports:
        - containerPort: 8761
