apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: johandiaz9021/user-service:latest
          ports:
            - containerPort: 8700
